name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.3
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.7"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.11.0
  rxdart: ^0.27.7
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
